version: '3.9'


services:
  app:
    user: '1000'
    ports:
      - '5000:5000' # Host - app
    command:
      - --host=0.0.0.0
    volumes:
      - ./source:/wd/source:rw
      - ./logs:/wd/logs:rw
      - ./output:/wd/output:rw
      - ./db:/wd/db:rw
