# Contains configuration settings for Black and Autoflake related to the project.
[tool.black]
line-length = 80
target-version = ['py311']
extend-exclude = '''
venv
'''

[tool.autoflake]
check = true
in-place = true
remove-unused-variables = true
remove-duplicate-keys = true
remove-all-unused-imports = true